apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loom
  namespace: flux-system
spec:
  interval: 1m
  path: "./"
  prune: true
  serviceAccountName: app-deployer
  sourceRef:
    kind: GitRepository
    name: loom
  targetNamespace: loom
---
apiVersion: v1
kind: Namespace
metadata:
  name: loom
