apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: loom
  namespace: flux-system
spec:
  interval: 1m
  url: https://codeberg.org/GEHACK/loom-deployment.git
  ref:
    branch: main
