apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gelift-tracker
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/GEWIS/gelift-tracker.git
  ref:
    branch: main
